services:
  auth_service:
    build: ./auth_service/
    hostname: auth_service
    env_file: ./.env
    environment:
      AUTH_SERVICE_DB_PASSWORD_FILE: /run/secrets/${AUTH_SERVICE_DB_PASSWORD_FILE}
      AUTH_SERVICE_SECRET_KEY_FILE: /run/secrets/${AUTH_SERVICE_SECRET_KEY_FILE} # for production
    depends_on:
      db:
        condition: service_started
    command: --env=${WORK_ENV}
    develop:
      watch:
        - action: sync
          path: ./auth_service/auth_service
          target: /app/auth_service/auth_service
    networks:
      - internal_network
      - external_network
    secrets:
      - auth_service_db_password
      - auth_service_secret_key
  
  db: 
    image: postgres
    hostname: ${AUTH_SERVICE_DB_HOSTNAME}
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/${AUTH_SERVICE_DB_PASSWORD_FILE}
      POSTGRES_DB: ${AUTH_SERVICE_DB_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_DB_USER}
    volumes:
      - auth_service_db:/var/lib/postgresql/data
    networks:
      - internal_network
    secrets:
      - auth_service_db_password

  nginx:
    build : ./nginx/
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - auth_service
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: ./etc/nginx/nginx.conf
    networks:
      - external_network

volumes:
  auth_service_db: {}

networks:
  external_network:
    driver: bridge
  internal_network:
    driver: bridge 

secrets:
  auth_service_db_password:
    file: ./secrets/${AUTH_SERVICE_DB_PASSWORD_FILE}
  auth_service_secret_key:
    file: ./secrets/${AUTH_SERVICE_SECRET_KEY_FILE}