worker_processes 1; #number of parallel processes (in production this number should be equal to number of CPU cores; use `auto`)

events{
    worker_connections 1024; #number of simultaneous connections per worker processes
}

#context block (http, mail, tcp/udp stream, etc.)
http{
    #tells nginx to include content-type of request
    include mime.types;

    #cluster of servers to be redirected to
    upstream auth_service {
        least_conn; #algorithm of load balancing
        server auth_service:5000;
    }

    #server block   
    #1. how to listen to connections
    #2. which domain the config applies
    #3. how to route the requests
    server{
        listen 8080;
        server_name localhost;
        location / {
            proxy_pass http://auth_service; #tells nginx to act as a proxy server to the given upstream 
            
            #needed by server to know the originial request
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Prefix /;
        }
    }
}